[package]
name = "signaling-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version="1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tungstenite = "0.23.0"
uuid = { version = "1.9.1", features = ["v4"] }
